## Задание 1
Реализуйте градиентный спуск с постоянный шагом (learning rate). Исследовать сходимость при различных значениях шага

In [127]:
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (20, 10)

In [128]:
def f(x):
    return 5 * (x[0] - 9) ** 2 + (x[1] - 7) ** 2


def partial(i, x):
    h = 1e-5
    x[i] = x[i] + h
    right = f(x)
    x[i] = x[i] - 2 * h
    left = f(x)
    x[i] = x[i] + h
    return (right - left) / (2 * h)


def grad(x):
    return [partial(i, x) for i in range(len(x))]

In [129]:
def GB(lr):
    epoch = 20
    x = [-20, -20]

    points = np.zeros((epoch, 2))
    points[0] = x
    for i in range(1, epoch):
        x = x - lr * np.array(grad(x))
        points[i] = x
    return points

In [130]:
points1 = GB(0.16)

In [131]:
points2 = GB(0.20)

In [132]:
points3 = GB(0.1)

In [133]:
points4 = GB(0.05)

In [136]:
import sys
np.set_printoptions(threshold=np.inf)

In [137]:
points1

array([[-20.        , -20.        ],
       [ 26.4       , -11.36      ],
       [ -1.44      ,  -5.4848    ],
       [ 15.264     ,  -1.489664  ],
       [  5.2416    ,   1.22702848],
       [ 11.25504   ,   3.07437937],
       [  7.646976  ,   4.33057797],
       [  9.8118144 ,   5.18479302],
       [  8.51291136,   5.76565925],
       [  9.29225318,   6.16064829],
       [  8.82464809,   6.42924084],
       [  9.10521115,   6.61188377],
       [  8.93687331,   6.73608096],
       [  9.03787601,   6.82053506],
       [  8.97727439,   6.87796384],
       [  9.01363536,   6.91701541],
       [  8.99181878,   6.94357048],
       [  9.00490873,   6.96162793],
       [  8.99705476,   6.97390699],
       [  9.00176714,   6.98225675]])

In [138]:
points2

array([[-20.        , -20.        ],
       [ 38.        ,  -9.2       ],
       [-19.99999999,  -2.72      ],
       [ 37.99999999,   1.168     ],
       [-19.99999998,   3.5008    ],
       [ 37.99999998,   4.90048   ],
       [-19.99999998,   5.740288  ],
       [ 37.99999998,   6.2441728 ],
       [-19.99999998,   6.54650368],
       [ 37.99999998,   6.7279022 ],
       [-19.99999997,   6.83674133],
       [ 37.99999997,   6.9020448 ],
       [-19.99999996,   6.94122688],
       [ 37.99999995,   6.96473613],
       [-19.99999995,   6.97884168],
       [ 37.99999994,   6.987305  ],
       [-19.99999995,   6.992383  ],
       [ 37.99999994,   6.9954298 ],
       [-19.99999993,   6.99725788],
       [ 37.99999993,   6.99835472]])

In [139]:
points3

array([[-20.        , -20.        ],
       [  9.        , -14.6       ],
       [  9.        , -10.28      ],
       [  9.        ,  -6.824     ],
       [  9.        ,  -4.0592    ],
       [  9.        ,  -1.84736   ],
       [  9.        ,  -0.077888  ],
       [  9.        ,   1.3376896 ],
       [  9.        ,   2.47015168],
       [  9.        ,   3.37612134],
       [  9.        ,   4.10089708],
       [  9.        ,   4.68071766],
       [  9.        ,   5.14457413],
       [  9.        ,   5.5156593 ],
       [  9.        ,   5.81252744],
       [  9.        ,   6.05002195],
       [  9.        ,   6.24001756],
       [  9.        ,   6.39201405],
       [  9.        ,   6.51361124],
       [  9.        ,   6.61088899]])

In [140]:
points4

array([[-20.        , -20.        ],
       [ -5.5       , -17.3       ],
       [  1.75      , -14.87      ],
       [  5.375     , -12.683     ],
       [  7.1875    , -10.7147    ],
       [  8.09375   ,  -8.94323   ],
       [  8.546875  ,  -7.348907  ],
       [  8.7734375 ,  -5.9140163 ],
       [  8.88671875,  -4.62261467],
       [  8.94335937,  -3.4603532 ],
       [  8.97167969,  -2.41431788],
       [  8.98583984,  -1.47288609],
       [  8.99291992,  -0.62559749],
       [  8.99645996,   0.13696226],
       [  8.99822998,   0.82326604],
       [  8.99911499,   1.44093943],
       [  8.9995575 ,   1.99684549],
       [  8.99977875,   2.49716094],
       [  8.99988937,   2.94744485],
       [  8.99994469,   3.35270036]])