## Задание 1
Реализуйте градиентный спуск с постоянный шагом (learning rate). Исследовать сходимость при различных значениях шага

Функция: $sin(x) + cos(x) + z^2$

In [43]:
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (20, 10)

In [44]:
def f(x):
    return 3 * (x[0] - 9) ** 2 + 3 * (x[1] - 8) ** 2 + 3 * (x[2] - 7) ** 2

def partial(i, x):
    h = 1e-5
    x[i] = x[i] + h
    right = f(x)
    x[i] = x[i] - 2 * h
    left = f(x)
    x[i] = x[i] + h
    return (right - left) / (2 * h)


def grad(x):
    return [partial(i, x) for i in range(len(x))]

In [45]:
def GB(lr):
    epoch = 50
    x = [-20, -20, -20]

    points = np.zeros((epoch, 3))
    points[0] = x
    for i in range(1, epoch):
        x = x - lr * np.array(grad(x))
        points[i] = x
    return points

In [46]:
points1 = GB(0.16)

In [47]:
points2 = GB(0.20)

In [48]:
points3 = GB(0.1)

In [49]:
import sys

np.set_printoptions(threshold=np.inf)

In [50]:
points1

array([[-20.        , -20.        , -20.        ],
       [  7.84      ,   6.87999999,  20.32      ],
       [  8.9536    ,   7.9552    ,  21.9328    ],
       [  8.998144  ,   7.998208  ,  21.997312  ],
       [  8.99992576,   7.99992832,  21.99989248],
       [  8.99999703,   7.99999713,  21.9999957 ],
       [  8.99999988,   7.99999989,  21.99999983],
       [  9.        ,   8.        ,  21.99999999],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.     

In [51]:
points2

array([[-20.        , -20.        , -20.        ],
       [ 14.79999999,  13.59999999,  30.4       ],
       [  7.84      ,   6.88      ,  20.32      ],
       [  9.232     ,   8.224     ,  22.336     ],
       [  8.9536    ,   7.9552    ,  21.9328    ],
       [  9.00928   ,   8.00896   ,  22.01344   ],
       [  8.998144  ,   7.998208  ,  21.997312  ],
       [  9.0003712 ,   8.0003584 ,  22.0005376 ],
       [  8.99992576,   7.99992832,  21.99989248],
       [  9.00001485,   8.00001434,  22.0000215 ],
       [  8.99999703,   7.99999713,  21.9999957 ],
       [  9.00000059,   8.00000057,  22.00000086],
       [  8.99999988,   7.99999989,  21.99999983],
       [  9.00000002,   8.00000002,  22.00000003],
       [  9.        ,   8.        ,  21.99999999],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.     

In [52]:
points3

array([[-20.        , -20.        , -20.        ],
       [ -2.6       ,  -3.20000001,   5.2       ],
       [  4.36      ,   3.52      ,  15.28      ],
       [  7.144     ,   6.208     ,  19.312     ],
       [  8.2576    ,   7.2832    ,  20.9248    ],
       [  8.70304   ,   7.71328   ,  21.56992   ],
       [  8.881216  ,   7.885312  ,  21.827968  ],
       [  8.9524864 ,   7.9541248 ,  21.9311872 ],
       [  8.98099456,   7.98164992,  21.97247488],
       [  8.99239782,   7.99265997,  21.98898995],
       [  8.99695913,   7.99706399,  21.99559598],
       [  8.99878365,   7.99882559,  21.99823839],
       [  8.99951346,   7.99953024,  21.99929536],
       [  8.99980538,   7.9998121 ,  21.99971814],
       [  8.99992215,   7.99992484,  21.99988726],
       [  8.99996886,   7.99996994,  21.9999549 ],
       [  8.99998754,   7.99998797,  21.99998196],
       [  8.99999502,   7.99999519,  21.99999278],
       [  8.99999801,   7.99999808,  21.99999711],
       [  8.9999992 ,   7.99999

Задание 2

In [53]:
def get_lr(n, start, k):
    return start * np.exp(-k * n)

In [54]:
def gb_with_exp_decay(lr):
    epoch = 50
    x = [-20, -20, -20]

    points = np.zeros((epoch, 3))
    points[0] = x
    for i in range(1, epoch):
        x = x - get_lr(i, lr, 0.01) * np.array(grad(x))
        points[i] = x
    return points

In [55]:
points1 = gb_with_exp_decay(0.16)
points1

array([[-20.        , -20.        , -20.        ],
       [  7.56298737,   6.61253952,  19.9188093 ],
       [  8.91520293,   7.91812696,  21.87719045],
       [  8.99420223,   7.99440215,  21.99160323],
       [  8.99954985,   7.99956537,  21.99934806],
       [  8.99996092,   7.99996227,  21.9999434 ],
       [  8.99999625,   7.99999638,  21.99999457],
       [  8.99999961,   7.99999962,  21.99999943],
       [  8.99999996,   7.99999996,  21.99999994],
       [  8.99999999,   7.99999999,  21.99999999],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.     

In [56]:
points2 = gb_with_exp_decay(0.2)
points2

array([[-20.        , -20.        , -20.        ],
       [ 14.45373421,  13.2656744 ,  29.89851162],
       [  8.03884257,   7.07198593,  20.60797889],
       [  9.15814369,   8.15269046,  22.22903569],
       [  8.97581234,   7.9766464 ,  21.9649696 ],
       [  9.00342196,   8.00330396,  22.00495594],
       [  8.99955474,   7.9995701 ,  21.99935515],
       [  9.00005293,   8.0000511 ,  22.00007666],
       [  8.9999943 ,   7.99999449,  21.99999174],
       [  9.00000055,   8.00000053,  22.0000008 ],
       [  8.99999995,   7.99999995,  21.99999993],
       [  9.        ,   8.        ,  22.00000001],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.        ,  22.        ],
       [  9.        ,   8.     

In [57]:
points3 = gb_with_exp_decay(0.1)
points3

array([[-20.        , -20.        , -20.        ],
       [ -2.7731329 ,  -3.3671628 ,   4.94925581],
       [  4.15087265,   3.31808394,  14.97712591],
       [  6.97436104,   6.04421066,  19.06631599],
       [  8.14208855,   7.1716717 ,  20.75750756],
       [  8.63173092,   7.64442985,  21.46664478],
       [  8.83982457,   7.84534787,  21.7680218 ],
       [  8.92943252,   7.93186588,  21.89779882],
       [  8.96851772,   7.96960331,  21.95440497],
       [  8.9857813 ,   7.9862716 ,  21.9794074 ],
       [  8.99350067,   7.99372478,  21.99058717],
       [  8.99699406,   7.99709771,  21.99564657],
       [  8.99859368,   7.99864217,  21.99796326],
       [  8.99933461,   7.99935755,  21.99903633],
       [  8.99968169,   7.99969266,  21.99953899],
       [  8.99984607,   7.99985138,  21.99977707],
       [  8.99992477,   7.99992737,  21.99989105],
       [  8.99996285,   7.99996413,  21.9999462 ],
       [  8.99998147,   7.99998211,  21.99997316],
       [  8.99999066,   7.99999

Задание 3

In [58]:
def u(a, x_k):
    return f(x_k - a * np.array(grad(x_k)))

Ищем отрезок, на котором есть минимум

In [59]:
def find_seg(x_k):
    # p2 - min; p1 - start; p3 - end
    a = 0.5
    ux_0 = u(0, x_k)
    ux_1 = u(a, x_k)
    ux_0c = x_k - 0 * np.array(grad(x_k))
    ux_1c = x_k - a * np.array(grad(x_k))

    p1, p2, p3, = 0, 0, 0
    if ux_1 < ux_0:
        a = a * 1.5
        ux_2 = u(a, x_k)
        ux_2c = x_k - a * np.array(grad(x_k))
        while ux_1 > ux_2:
            ux_1 = ux_2
            ux_1c = ux_2c
            a *= 1.5
            ux_2 = u(a, x_k)
            ux_2c = x_k - a * np.array(grad(x_k))
        p1 = 0
        p2 = ux_1c
        p3 = a
    elif ux_1 > ux_0:
        p1 = 0
        p3 = a
        # a = a / 1.5
        # ux_2 = u(a, x_k)
        # ux_2c = x_k - a * np.array(grad(x_k))
        # while ux_2 > ux_0:
        #     # ux_1 = ux_2
        #     # ux_1c = ux_2c
        #     a = a / 1.5
        #     ux_2 = u(a, x_k)
        #     ux_2c = x_k - a * np.array(grad(x_k))
        #
        # p2 = ux_2c
        # p3 = ux_1c

    return [p1, p3]

In [60]:
def dih(a, b, x_k):
    h = 1e-5
    for i in range(100):
        m = (a + b) / 2
        left = u(m - h, x_k)
        right = u(m + h, x_k)
        if left < right:
            b = m + h
            # b = x_k - (m+h) * np.array(grad(x_k))
        elif left > right:
            a = m - h
            # a = x_k - (m-h) * np.array(grad(x_k))
    return x_k - a * np.array(grad(x_k))

In [61]:
x = [-20, -20, -20]
for i in range(20):
    seg = find_seg(x)
    x = dih(seg[0], seg[1], x)
x

array([ 9.,  8., 22.])