## Задание 1
Реализуйте градиентный спуск с постоянный шагом (learning rate). Исследовать сходимость при различных значениях шага

In [145]:
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (20, 10)

In [146]:
def f(x):
    return 5 * (x[0] - 9) ** 2 + (x[1] - 7) ** 2 + 3 * (x[2] - 4) ** 2


def partial(i, x):
    h = 1e-5
    x[i] = x[i] + h
    right = f(x)
    x[i] = x[i] - 2 * h
    left = f(x)
    x[i] = x[i] + h
    return (right - left) / (2 * h)


def grad(x):
    return [partial(i, x) for i in range(len(x))]

In [147]:
def GB(lr):
    epoch = 20
    x = [-20, -20, -20]

    points = np.zeros((epoch, 3))
    points[0] = x
    for i in range(1, epoch):
        x = x - lr * np.array(grad(x))
        points[i] = x
    return points

In [148]:
points1 = GB(0.16)

In [149]:
points2 = GB(0.20)

In [150]:
points3 = GB(0.1)

In [151]:
points4 = GB(0.05)

In [152]:
import sys

np.set_printoptions(threshold=np.inf)

In [153]:
points1

array([[-20.        , -20.        , -20.        ],
       [ 26.4       , -11.36      ,   3.04      ],
       [ -1.44      ,  -5.4848    ,   3.9616    ],
       [ 15.264     ,  -1.489664  ,   3.998464  ],
       [  5.2416    ,   1.22702848,   3.99993856],
       [ 11.25504   ,   3.07437937,   3.99999754],
       [  7.646976  ,   4.33057797,   3.9999999 ],
       [  9.8118144 ,   5.18479302,   4.        ],
       [  8.51291136,   5.76565925,   4.        ],
       [  9.29225318,   6.16064829,   4.        ],
       [  8.82464809,   6.42924084,   4.        ],
       [  9.10521115,   6.61188377,   4.        ],
       [  8.93687331,   6.73608096,   4.        ],
       [  9.03787601,   6.82053506,   4.        ],
       [  8.97727439,   6.87796384,   4.        ],
       [  9.01363536,   6.91701541,   4.        ],
       [  8.99181878,   6.94357048,   4.        ],
       [  9.00490873,   6.96162793,   4.        ],
       [  8.99705476,   6.97390699,   4.        ],
       [  9.00176714,   6.98225

In [154]:
points2

array([[-20.        , -20.        , -20.        ],
       [ 38.        ,  -9.2       ,   8.8       ],
       [-19.99999999,  -2.72      ,   3.04000001],
       [ 37.99999999,   1.168     ,   4.19199999],
       [-19.99999998,   3.5008    ,   3.96160001],
       [ 37.99999998,   4.90048   ,   4.00768   ],
       [-19.99999998,   5.740288  ,   3.99846399],
       [ 37.99999998,   6.2441728 ,   4.0003072 ],
       [-19.99999998,   6.54650368,   3.99993857],
       [ 37.99999998,   6.7279022 ,   4.00001228],
       [-19.99999997,   6.83674133,   3.99999754],
       [ 37.99999997,   6.9020448 ,   4.00000049],
       [-19.99999996,   6.94122688,   3.9999999 ],
       [ 37.99999995,   6.96473613,   4.00000002],
       [-19.99999995,   6.97884168,   3.99999999],
       [ 37.99999994,   6.987305  ,   4.        ],
       [-19.99999995,   6.992383  ,   4.        ],
       [ 37.99999994,   6.9954298 ,   4.        ],
       [-19.99999993,   6.99725788,   4.        ],
       [ 37.99999993,   6.99835

In [155]:
points3

array([[-20.        , -20.        , -20.        ],
       [  9.        , -14.6       ,  -5.6       ],
       [  9.        , -10.28      ,   0.16      ],
       [  9.        ,  -6.824     ,   2.464     ],
       [  9.        ,  -4.0592    ,   3.3856    ],
       [  9.        ,  -1.84736   ,   3.75424   ],
       [  9.        ,  -0.077888  ,   3.901696  ],
       [  9.        ,   1.3376896 ,   3.9606784 ],
       [  9.        ,   2.47015168,   3.98427136],
       [  9.        ,   3.37612134,   3.99370854],
       [  9.        ,   4.10089708,   3.99748342],
       [  9.        ,   4.68071766,   3.99899337],
       [  9.        ,   5.14457413,   3.99959735],
       [  9.        ,   5.5156593 ,   3.99983894],
       [  9.        ,   5.81252744,   3.99993558],
       [  9.        ,   6.05002195,   3.99997423],
       [  9.        ,   6.24001756,   3.99998969],
       [  9.        ,   6.39201405,   3.99999588],
       [  9.        ,   6.51361124,   3.99999835],
       [  9.        ,   6.61088

In [156]:
points4

array([[-20.        , -20.        , -20.        ],
       [ -5.5       , -17.3       , -12.8       ],
       [  1.75      , -14.87      ,  -7.76      ],
       [  5.375     , -12.683     ,  -4.232     ],
       [  7.1875    , -10.7147    ,  -1.7624    ],
       [  8.09375   ,  -8.94323   ,  -0.03368   ],
       [  8.546875  ,  -7.348907  ,   1.176424  ],
       [  8.7734375 ,  -5.9140163 ,   2.0234968 ],
       [  8.88671875,  -4.62261467,   2.61644776],
       [  8.94335937,  -3.4603532 ,   3.03151343],
       [  8.97167969,  -2.41431788,   3.3220594 ],
       [  8.98583984,  -1.47288609,   3.52544158],
       [  8.99291992,  -0.62559749,   3.66780911],
       [  8.99645996,   0.13696226,   3.76746638],
       [  8.99822998,   0.82326604,   3.83722646],
       [  8.99911499,   1.44093943,   3.88605852],
       [  8.9995575 ,   1.99684549,   3.92024097],
       [  8.99977875,   2.49716094,   3.94416868],
       [  8.99988937,   2.94744485,   3.96091807],
       [  8.99994469,   3.35270