## Задание 1
Реализуйте градиентный спуск с постоянный шагом (learning rate). Исследовать сходимость при различных значениях шага

Функция: $sin(x) + cos(x) + z^2$

In [385]:
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (20, 10)

In [386]:
def f(x):
    return 5 * (x[0] - 9) ** 2 + (x[1] - 7) ** 2 + 3 * (x[2] - 4) ** 2



def partial(i, x):
    h = 1e-5
    x[i] = x[i] + h
    right = f(x)
    x[i] = x[i] - 2 * h
    left = f(x)
    x[i] = x[i] + h
    return (right - left) / (2 * h)


def grad(x):
    return [partial(i, x) for i in range(len(x))]

In [387]:
def GB(lr):
    epoch = 50
    x = [-20, -20, -20]

    points = np.zeros((epoch, 3))
    points[0] = x
    for i in range(1, epoch):
        x = x - lr * np.array(grad(x))
        points[i] = x
    return points

In [388]:
points1 = GB(0.16)

In [389]:
points2 = GB(0.20)

In [390]:
points3 = GB(0.1)

In [391]:
import sys

np.set_printoptions(threshold=np.inf)

In [392]:
points1

array([[-20.        , -20.        , -20.        ],
       [ 26.4       , -11.36      ,   3.04      ],
       [ -1.44      ,  -5.4848    ,   3.9616    ],
       [ 15.264     ,  -1.489664  ,   3.998464  ],
       [  5.2416    ,   1.22702848,   3.99993856],
       [ 11.25504   ,   3.07437937,   3.99999754],
       [  7.646976  ,   4.33057797,   3.9999999 ],
       [  9.8118144 ,   5.18479302,   4.        ],
       [  8.51291136,   5.76565925,   4.        ],
       [  9.29225318,   6.16064829,   4.        ],
       [  8.82464809,   6.42924084,   4.        ],
       [  9.10521115,   6.61188377,   4.        ],
       [  8.93687331,   6.73608096,   4.        ],
       [  9.03787601,   6.82053506,   4.        ],
       [  8.97727439,   6.87796384,   4.        ],
       [  9.01363536,   6.91701541,   4.        ],
       [  8.99181878,   6.94357048,   4.        ],
       [  9.00490873,   6.96162793,   4.        ],
       [  8.99705476,   6.97390699,   4.        ],
       [  9.00176714,   6.98225

In [393]:
points2

array([[-20.        , -20.        , -20.        ],
       [ 38.        ,  -9.2       ,   8.8       ],
       [-19.99999999,  -2.72      ,   3.04000001],
       [ 37.99999999,   1.168     ,   4.19199999],
       [-19.99999998,   3.5008    ,   3.96160001],
       [ 37.99999998,   4.90048   ,   4.00768   ],
       [-19.99999998,   5.740288  ,   3.99846399],
       [ 37.99999998,   6.2441728 ,   4.0003072 ],
       [-19.99999998,   6.54650368,   3.99993857],
       [ 37.99999998,   6.7279022 ,   4.00001228],
       [-19.99999997,   6.83674133,   3.99999754],
       [ 37.99999997,   6.9020448 ,   4.00000049],
       [-19.99999996,   6.94122688,   3.9999999 ],
       [ 37.99999995,   6.96473613,   4.00000002],
       [-19.99999995,   6.97884168,   3.99999999],
       [ 37.99999994,   6.987305  ,   4.        ],
       [-19.99999995,   6.992383  ,   4.        ],
       [ 37.99999994,   6.9954298 ,   4.        ],
       [-19.99999993,   6.99725788,   4.        ],
       [ 37.99999993,   6.99835

In [394]:
points3

array([[-20.        , -20.        , -20.        ],
       [  9.        , -14.6       ,  -5.6       ],
       [  9.        , -10.28      ,   0.16      ],
       [  9.        ,  -6.824     ,   2.464     ],
       [  9.        ,  -4.0592    ,   3.3856    ],
       [  9.        ,  -1.84736   ,   3.75424   ],
       [  9.        ,  -0.077888  ,   3.901696  ],
       [  9.        ,   1.3376896 ,   3.9606784 ],
       [  9.        ,   2.47015168,   3.98427136],
       [  9.        ,   3.37612134,   3.99370854],
       [  9.        ,   4.10089708,   3.99748342],
       [  9.        ,   4.68071766,   3.99899337],
       [  9.        ,   5.14457413,   3.99959735],
       [  9.        ,   5.5156593 ,   3.99983894],
       [  9.        ,   5.81252744,   3.99993558],
       [  9.        ,   6.05002195,   3.99997423],
       [  9.        ,   6.24001756,   3.99998969],
       [  9.        ,   6.39201405,   3.99999588],
       [  9.        ,   6.51361124,   3.99999835],
       [  9.        ,   6.61088

Задание 2

In [395]:
def get_lr(n, start, k):
    return start * np.exp(-k*n)

In [396]:
def gb_with_exp_decay(lr):
    epoch = 50
    x = [-20, -20, -20]

    points = np.zeros((epoch, 3))
    points[0] = x
    for i in range(1, epoch):
        x = x - get_lr(i, lr, 0.01) * np.array(grad(x))
        points[i] = x
    return points

In [397]:
points1 = gb_with_exp_decay(0.16)
points1

array([[-20.        , -20.        , -20.        ],
       [ 25.93831229, -11.44596944,   2.81074817],
       [ -0.62634568,  -5.66014071,   3.92982311],
       [ 14.32060499,  -1.72862807,   3.99520185],
       [  6.14143525,   0.9550115 ,   3.99962746],
       [ 10.49207669,   2.7950662 ,   3.99996766],
       [  8.24378084,   4.06228461,   3.9999969 ],
       [  9.37193136,   4.93879906,   3.99999967],
       [  8.82259389,   5.54767211,   3.99999996],
       [  9.08201305,   5.97241699,   4.        ],
       [  8.96327949,   6.26995157,   4.        ],
       [  9.01591227,   6.47923231,   4.        ],
       [  8.9933316 ,   6.62703375,   4.        ],
       [  9.00270039,   6.73183374,   4.        ],
       [  8.99894422,   6.80643615,   4.        ],
       [  9.00039817,   6.85974878,   4.        ],
       [  8.99985529,   6.89799332,   4.        ],
       [  9.00005063,   6.92553235,   4.        ],
       [  8.99998297,   6.94543654,   4.        ],
       [  9.0000055 ,   6.95987

In [398]:
points2 = gb_with_exp_decay(0.2)
points2

array([[-20.        , -20.        , -20.        ],
       [ 37.42289036,  -9.3074618 ,   8.51343521],
       [-18.29726848,  -2.91364082,   3.20455937],
       [ 34.68375607,   0.93461856,   4.13087754],
       [-14.66960711,   3.26564033,   3.97998263],
       [ 30.36084638,   4.68653345,   4.00283196],
       [ -9.87292867,   5.55802975,   3.99963151],
       [ 25.32107544,   6.09582341,   4.0000438 ],
       [ -4.81142762,   6.42968749,   3.99999528],
       [ 20.43396121,   6.63817804,   4.00000046],
       [ -0.25779067,   6.76913406,   3.99999996],
       [ 16.32909913,   6.8518611 ,   4.        ],
       [  3.32844353,   6.90441607,   4.        ],
       [ 13.28877917,   6.93798879,   4.        ],
       [  5.83180819,   6.95955277,   4.        ],
       [ 11.28558412,   6.97347807,   4.        ],
       [  7.3902915 ,   6.98251827,   4.        ],
       [ 10.10640035,   6.98841776,   4.        ],
       [  8.25811384,   6.99228748,   4.        ],
       [  9.48513291,   6.99483

In [399]:
points3 = gb_with_exp_decay(0.1)
points3

array([[-20.        , -20.        , -20.        ],
       [  8.71144518, -14.6537309 ,  -5.74328239],
       [  8.99428623, -10.40873924,  -0.01307091],
       [  8.99983113,  -7.02989259,   2.32360913],
       [  8.99999338,  -4.33393806,   3.29000432],
       [  8.99999968,  -2.17770299,   3.69522559],
       [  8.99999998,  -0.44905595,   3.86744103],
       [  9.        ,   0.94003479,   3.94159933],
       [  9.        ,   2.05884538,   3.9739457 ],
       [  9.        ,   2.96202044,   3.9882328 ],
       [  9.        ,   3.69276344,   3.99462124],
       [  9.        ,   4.28531052,   3.99751233],
       [  9.        ,   4.76685324,   3.99883615],
       [  9.        ,   5.15903643,   3.99944933],
       [  9.        ,   5.4791278 ,   3.99973657],
       [  9.        ,   5.74093317,   3.99987261],
       [  9.        ,   5.95551436,   3.99993774],
       [  9.        ,   6.13175352,   3.99996926],
       [  9.        ,   6.2767976 ,   3.99998466],
       [  9.        ,   6.39640